### ISSUE TITLE
Cinnamon and menu button/icon

### ISSUE THREAD

**Issue by ssepan2** [B00merang-Project/Windows-XP#12]
As suggested in the pling.com blog, I am posting these here too...
-This first issue I initially thought was something in the themes, but later determined that it occured independently of the selected theme (yours or otherwise) and is almost certainly metacity. I only mention it here in the hope that you have run across it. Some time in between upgrading from Mint 19.1 to 19.2 I lost the application icon that appears in the upper-left corner of the windows where the window-menu is activated. (System Settings|Windows|Titlebar tab|Buttons group|'Left side title bar buttons'|first-drop-down="Menu") After doing some testing in two virtual machines running (linux Mint Cinnamon) 19.1 and 19.2 respectively, I was able to determine that this issue is with a change in Linux Mint (Cinnamon) 19.2, because all 3 versions display the application icon in 19.1 and do not display it in 19.2. (Mint themes display an arrow in 19.1 and no arrow in 19.2). As I said, not an issue *with the themes*, but any insight appreciated...

Update: I ran across a link somewhere that I unfortunately don't have here but it was indicated (hearesay) that this was a change in Cinnamon for 19.2 to no longer handle the metacity tag "icon". It sure seems to be the case. I resolved this by noting that MintX and MintY displayed an arrow, and I borrowed from MintY and made lighter/darker versions to handle the focused/unfocused/highlighted events. Then I had to edit a bunch for "frame_style" tags of different "geometry=..." configurations. 

I can make the modified theme files available to you upon request.

![Screenshot from 2019-09-23 08-55-57](https://user-images.githubusercontent.com/7924858/65440137-402e9a00-ddf6-11e9-844e-205bde3cfeb4.png)
![Screenshot from 2019-09-23 08-57-25](https://user-images.githubusercontent.com/7924858/65440139-40c73080-ddf6-11e9-8b7c-5447096bd921.png)

**Comment by ssepan2** [comment]
-Some dialogs would benefit from retaining the Close button. (In Linux Mint Cinnamon) set 'Windows XP Royale' theme; open Nemo, select 'Edit | Preferences', close dialog (client area has no Close button, so you go looking for Close button on dialog frame, but must resort to right-click titlebar and choose close). Find /home/username/.themes/Windows XP Royale/metacity-1/metacity-3.xml, and edit "" and change to hide_buttons="false. I like that this also brings back access to the upper-left window-menu (even though no icon or arrow appears).
Update: I seem to recall that I resolved this by altering (removing?) a tag such as:
"<frame_geometry name="nobuttons" hide_buttons=...."

**Comment by ssepan2** [comment]
- In 'Windows XP Royale', everything is beautiful except the Calendar applet in the system-tray: the light font on the light background is unreadable. I've spent some time looking for tags that affect the font and the only clue I've got that it can be changed is in the Mint and Mint X themes with their dark calendar font -- other than that I have not been able to find anthing that changes it. For now I resorted to making the background image darker: /home/username/.themes/Windows XP Royale/cinnamon/panel-right.png. Windows XP Metallic also suffers from this issue, and Homestead is so-so. I know darkening the right panel departs from the original theme, but unless the text can be darkened, this is a practical work-around. If you know where that is controlled, please let me know.
Update: regarding the 3rd item in my comments (date/time in right panel)...
I found setting this works well enough that I can reverse the change of panel-right.png:
/*calendar applet font color fix*/
#panelRight .applet-label {
color: #444444;
font-weight: bold;
text-shadow: #000000;
} 
screenshot, after:
![Screenshot from 2019-09-23 11-47-03](https://user-images.githubusercontent.com/7924858/65441074-c5ff1500-ddf7-11e9-8995-253579452679.png)

**Comment by ssepan2** [comment]
- The text in the pop-up date menu is as hard-to-read as the Calendar applet (foreground / background both light), but it can be fixed by darkening some color hex values for certain 'calendar' tags in the ' Date applet' secton of /home/username/.themes/Windows XP Royale/cinnamon/cinnamon.css. Frankly, Royale Dark and Zune could also use the same tweak. Metalic, Luna and Homestead actually look pretty good there. This too I can share upon request.
screenshot, after:
![Screenshot from 2019-09-23 11-52-13a](https://user-images.githubusercontent.com/7924858/65441928-440feb80-ddf9-11e9-9e42-1cbaa2090448.png)

**Comment by ssepan2** [comment]
(sigh) sorry about the 2nd, 3rd, 4th issue as comments instead of separate issues;  I will try to delete adn re-submit those 3--SJS

**Comment by Elbullazul** [comment]
can you submit your changes as a pull request?

**Comment by ssepan2** [comment]
OK, will take a shot at it (PR)...

**Comment by ssepan2** [comment]
Another note as I start working on this: as you'll note from the two tiny screenshots above, I added more than just the menu arrow to my copy, but this issue #12) will be limited to that button / icon, and I'm going to introduce a separate issue for the additional button / icons (sticky, shade).

**Comment by ssepan2** [comment]
Note also that I'm basing each PR on master, so changes from the other PRs will not be reflected in each PR. As two of the PRs affect one file (metacity-theme-3.xml) and two  others affect a second file (cinnamon.css), it is important to note that changes in a given PR do not account for the others. I supposed normally I would not be doing 4 in quick succession and would be re-basing  (I think that is the term I read) each PR, but that is not the case here.

**Comment by Elbullazul** [comment]
@ssepan2 no problem. conflicts shouldn't appear unless you edited the same line(s) in multiple commits

for the buttons, I'm still planning on rebasing metacity themes on a more modern base (current causes issues with firefox), so maybe it won't make it into master. Submit it anyways, because I'm unsure when I'll have time to make a new version

**Comment by ssepan2** [comment]
Cool. Nope, different lines.
OK, I'll submit it just in case it can be used. Thx

**Comment by Elbullazul** [comment]
139de747f17ba5b4bb196d1b6eb6f2bd3ab90793 and 26843c4eae95908ba78954e627508e155129e2e9 fixes this
