### ISSUE TITLE
Calendar applet in sys tray: font forecolor

### ISSUE THREAD

**Issue by ssepan2** [B00merang-Project/Windows-XP#14]
In 'Windows XP Royale', everything is beautiful except the Calendar applet in the system-tray: the light font on the light background is unreadable. I've spent some time looking for tags that affect the font and the only clue I've got that it can be changed is in the Mint and Mint X themes with their dark calendar font -- other than that I have not been able to find anthing that changes it. For now I resorted to making the background image darker: /home/username/.themes/Windows XP Royale/cinnamon/panel-right.png. Windows XP Metallic also suffers from this issue, and Homestead is so-so. I know darkening the right panel departs from the original theme, but unless the text can be darkened, this is a practical work-around. If you know where that is controlled, please let me know.
Update: regarding the item in my comments (date/time in right panel)...
I found setting this works well enough that I can reverse the change of panel-right.png:
/calendar applet font color fix/
#panelRight .applet-label {
color: #444444;
font-weight: bold;
text-shadow: #000000;
}
screenshot, after:
![Screenshot from 2019-09-23 11-47-03](https://user-images.githubusercontent.com/7924858/65443812-c64ddf00-ddfc-11e9-9da0-be2d4a8958fd.png)

**Comment by Elbullazul** [comment]
Wasn't aware right panel applets had a light text on the panel. I'll try to update this when possible

**Comment by ssepan2** [comment]
While I'm on a roll here, I'll try and create a PR for you to inspect...
