### ISSUE TITLE
Calendar applet *popup*; multiple items font forecolor

### ISSUE THREAD

**Issue by ssepan2** [B00merang-Project/Windows-XP#15]
The text in the pop-up date menu is as hard-to-read as the Calendar applet (foreground / background both light), but it can be fixed by darkening some color hex values for certain 'calendar' tags in the ' Date applet' secton of /home/username/.themes/Windows XP Royale/cinnamon/cinnamon.css. Frankly, Royale Dark and Zune could also use the same tweak. Metalic, Luna and Homestead actually look pretty good there. This too I can share upon request.
screenshot, after:
![Screenshot from 2019-09-23 11-52-13a](https://user-images.githubusercontent.com/7924858/65443958-0dd46b00-ddfd-11e9-9854-ce5b43eaedfa.png)

**Comment by Elbullazul** [comment]
Can you submit a PR with the changes the calendar tags only?

Or can you post what rules you changed to get dark text?

**Comment by ssepan2** [comment]
OK, will look into doing PR...

**Comment by ssepan2** [comment]
installed git on my Linux Mint, added GitHub Pull Request extension to VS Code on Mint, cloned master to a Git folder under 'home' and can see files in VSCode.

Trying a pull request from VSCode produces error 'Creating pull requests for 'B00merang-Project:master' failed: Validation Failed: No commits between master and master'.

Trying a pull request from the web page, can't tell what I am supposed to do with that at all. 

I only used Git a little from VS2012 on Windows in private network back in 2014-2016, and have done no coding for a few years. No experience w/ GitHub, but I blundered my way through the addition of the VSCode extension yesterday, and thought I'd be able to get all the way to a checkout or something.

Will try a little more, but if I can't figure this out, I will have to just post the CSS rule changes in the comments here.
--Steve

**Comment by ssepan2** [comment]
commited changes locally, still get error on pull request: 'Creating pull requests for 'B00merang-Project:master' failed: Validation Failed: No commits between master and master'

**Comment by ssepan2** [comment]
Did a commit to the local repository, then tried a  syncronize from the VSCode status-bar. Was asked for username/password, entered github login, told 'Permission to B00merang-Project/Windows-XP.git denied to ssepan2'. Tried Pull Request from inside VSCode one more time, same error as before.

**Comment by Elbullazul** [comment]
Can you post what changes you made to change the calendar colors?

**Comment by ssepan2** [comment]
This is the whole Date applet section from cinnamon.css. Changes / additions bolded. Some of the comments I added are missing asterisks when posted in this comment:
`/* ===================================================================
 * Date applet 
 * ===================================================================*/

.calendar {
    padding: .4em 1.75em;
    spacing-rows: 0px;
    spacing-columns: 0px;
}

.calendar-month-label {
    **color: #888;**
    font-size: 7.5pt;
    padding-bottom: 8px;
    padding-top: 8px;
    font-weight: bold;
}

.calendar-change-month-back {
    width: 18px;
    height: 12px;
    background-image: url("calendar-arrow-left.svg");
    border-radius: 4px;
    border: 1px solid rgba(0,0,0,0);
}

.calendar-change-month-back:rtl {
    background-image: url("calendar-arrow-right.svg");
}
**/*month/year left arrow*/**
.calendar-change-month-back:hover {
    background-color: rgba(**96,96,96**,0.5);
}
.calendar-change-month-back:active {
    background-color: rgba(255,255,255,0.5);
}

.calendar-change-month-forward {
    width: 18px;
    height: 12px;
    background-image: url("calendar-arrow-right.svg");
    border-radius: 4px;
    border: 1px solid rgba(0,0,0,0);
}

.calendar-change-month-forward:rtl {
    background-image: url("calendar-arrow-left.svg");
}
**/*month/year right arrow*/**
.calendar-change-month-forward:hover {
    background-color: rgba(**96,96,96**,0.5);
}

.calendar-change-month-forward:active {
    background-color: rgba(255,255,255,0.5);
}
**/*day/date header*/**
.datemenu-date-label {
    padding: .4em 1.75em;
    font-size: 10.5pt;
    color: #**444**;
}

.calendar-day-base {
    font-size: 7.5pt;
    text-align: center;
    width: 2.4em;
    height: 2.4em;
}

.calendar-day-base:hover {
    background-color: #399cee;
    color: #fff;
}

.calendar-day-base:active {
}
**/*day of week*/**
.calendar-day-heading {
    color: #**888**;
    padding-top: 1em;
    **font-weight: bold;**
}

.calendar-week-number {
    **background-**color: #fff;
    **color: #888;**
}

/* Hack used in lieu of border-collapse - see calendar.js */
.calendar-day {
    **background-**color: #**f8f8f8**;
    **color: #444;**
    border-top-width: 0;
    border-left-width: 0;
}
.calendar-day-top {
}
.calendar-day-left {
}

.calendar-work-day {
}

.calendar-nonwork-day {
    background-color: **#efefef;**
    **color: #444;**
}

.calendar-today {
    color: #ffffff;
    font-weight: bold;
    background-color: rgba(57,156,238,1);
    border-radius: 2px;
}

.calendar-other-month-day {
    color: #**888**;
}

.calendar-day-with-events {
    font-weight: bold;
    color: #399cee;
}`

**Comment by Elbullazul** [comment]
great, will look to integrate your changes into master

**Comment by ssepan2** [comment]
Cool. FYI, as the following screenshot shows, the changes above incorporate a little more than in the original screenshot, because I felt that there was more that could be done. Use as much or as little as you see fit.

![Screenshot from 2019-09-24 22-49-23](https://user-images.githubusercontent.com/7924858/65565442-e2956d00-df1d-11e9-8f49-0c82fd9886a9.png)

**Comment by ssepan2** [comment]
FYI -- did some more reading yesterday/today, and figured out that I need to 1) fork the repository to my account, 2) clone THAT, 3) create a BRANCH from THAT, 4) THEN make my changes, 5) Stage (this I remember from using Git before in an in-house repository), 6) Commit (ditto), 7) Push from VSCode (also remember this from before), 8) THEN do a Pull Request.

This site was helpful... [https://www.thinkful.com/learn/github-pull-request-tutorial/#Time-to-Submit-Your-First-PR](https://www.thinkful.com/learn/github-pull-request-tutorial/#Time-to-Submit-Your-First-PR)

**Comment by Roker2** [comment]
Hi! I use Cinnamon too. Developer didn't merge fix by @ssepan2. Will it fixed?

**Comment by Roker2** [comment]
I can fix all 7 themes, if you want.

**Comment by Elbullazul** [comment]
Hasn't it been fixed? I pushed some cinnamon changes a couple of weeks ago

**Comment by Roker2** [comment]
https://ibb.co/G9xB7LV
Check. I don't see arrows and titles.

**Comment by Roker2** [comment]
And maybe you need it... I booted my old computer and create screenshot.
https://ibb.co/W2YVJhq

**Comment by Roker2** [comment]
Oh, sorry. I thought, that it is topic with my problem, but my problem and this old problem are not same... I can create new topic.

**Comment by Elbullazul** [comment]
Are you using the latest master release? I thought this was fixed. But I think the issue is still the same so no need to create a new one
