### ISSUE TITLE
No Sticky, Shade images for titlebar buttons.

### ISSUE THREAD

**Issue by ssepan2** [B00merang-Project/Windows-XP#20]
While researching issue #12, I noticed that some other themes (ex: MintX, MintY) not only had a menu button image instead of nothing on Mint 19.2, they also had images available for some additional features such as Shade and Sticky (which were not implemented in the Windows XP themes presumably because they had no analogue in Windows). I found the ones in MintY the most intuitive, and used those in my copy of the themes.

I am proposing an enhancement to all seven themes along the lines of what I came up with here. This is an interface for a  pair of features which are a capability of windows in Linux Mint but which are not enabled as titlebar buttons by default. My justification is that even though they depart from the appearance of Windows XP, there is no reason that Linux windows need to be hobbled. On the contrary, the themes are really intended to ease Windows users into the world of Linux. Another way to think of it is that cordless phones and mobile phones use a lot of terms and concepts inherited from older phones, but the analogy is not extended to far as to require a cord or to bolt them to a wall. ;-)

Granted the Sticky feature can be accessed by right-clicking on the titlebar ('Always on visible workspace'), but the Shade feature cannot, and I find access to the Sticky feature easier when using the button.

![Screenshot from 2019-09-23 08-55-20](https://user-images.githubusercontent.com/7924858/65730431-b7cb2600-e08f-11e9-8465-a082da24b9b5.png)
![Screenshot from 2019-09-23 08-55-57](https://user-images.githubusercontent.com/7924858/65730433-b994e980-e08f-11e9-800a-2b02e8ef508f.png)
![Screenshot from 2019-09-23 08-56-56](https://user-images.githubusercontent.com/7924858/65730435-ba2d8000-e08f-11e9-93d7-ed9989518e03.png)
![Screenshot from 2019-09-23 08-57-25](https://user-images.githubusercontent.com/7924858/65730437-bac61680-e08f-11e9-9d53-5be9b9187762.png)
![Screenshot from 2019-09-27 07-53-08](https://user-images.githubusercontent.com/7924858/65767451-eb439a00-e0fb-11e9-95e4-b2abfefc05c7.png)

Note that  the  button images described will only be visible if user goes to System Setting | Windows dialog | Titlebar tab | Buttons section | left/right title bar buttons, and selects 'Sticky' or 'Shade'.

**Comment by Elbullazul** [comment]
I can merge this into a new branch and integrate the min max button background into it, so that it looks better integrated (although our looks quite good rn)

**Comment by ssepan2** [comment]
PR submitted.
I have also put together a .ZIP file containing the original .SVG files borrowed from MintY and the set up light/dark .PNG variations that I created and used to modify this set of themes.

**Comment by Elbullazul** [comment]
Found some time to work a little bit on migrating to newer sources. Managed to do this:

![Luna metacity-3](https://user-images.githubusercontent.com/15310985/65839687-a37c6880-e2dd-11e9-99b7-ac1b33194f71.png)

which I think looks better integrated into the overall theme. What do you think?

BTW I'll probably merge your changes nonetheless, since it may be a while before I finish migrating everything

**Comment by ssepan2** [comment]
*Very* nice -- much more consistent look with the button 'frame' added behind.

Steve

**Comment by Elbullazul** [comment]
139de747f17ba5b4bb196d1b6eb6f2bd3ab90793 and 26843c4eae95908ba78954e627508e155129e2e9 fox this
