### ISSUE TITLE
Maximized button icon does not change when window is maximized

### ISSUE THREAD

**Issue by MrPaulBlack** [B00merang-Project/Windows-XP#24]
### *Description:*
The button to maximize windows does not change when a window gets maximized.

### *Note:*
* A Linux theme that successfully implements such a thing is the following for code inspiration: https://github.com/grassmunk/Chicago95

### *Repro:*
* apply windows XP Luna theme on xfce 4.14 to the window manager
* maximize a window
* observe as the window maximize button stays the same

### *Expected Result:*
* The maximize window icon should change when the window is maximized as seen in the first image

### *Images:*
* ![image](https://user-images.githubusercontent.com/38733246/82766292-e4386d00-9deb-11ea-856b-0cc0c9aca298.png) (when full-screen and the window is not focused, this is missing from the theme)
*  ![image](https://user-images.githubusercontent.com/38733246/82766313-0c27d080-9dec-11ea-8cc5-3816a46089ce.png) (when focused window is not full-screen)

**Comment by Elbullazul** [comment]
thought it was already implemented. Oh well, it won't be very hard to fix

**Comment by Elbullazul** [comment]
f3f1788 (finally) adds this feature, sorry for the delay
