### ISSUE TITLE
The Cinnamon Window List is not showing up properly

### ISSUE THREAD

**Issue by daemonspudguy** [B00merang-Project/Windows-XP#3]
The Cinnamon Window List has buttons that are too small. Unfortunately, I cannot show you because my Motherboard is fried.

**Comment by feren** [comment]
That arose in Cinnamon 3.4 onwards...

**Comment by Elbullazul** [comment]
I have no dev environment, had to install win10 for college and grub died, also newest ubuntu is missing a few drivers for my laptop, gonna install it on an old PC but have to wait for psu and ram to get here first...

and VM development is out of question, but will add this to the to do list

**Comment by feren** [comment]
@Elbullazul GRUB Died, more like Windows 10 Hosed it.

**Comment by jacobpoo** [comment]
@feren Nice.

**Comment by jacobpoo** [comment]
@feren @Elbullazul Good news, my motherboard has been replaced, along with a new AMD A8 CPU with another stick of 4 gigabytes, totaling 8.

**Comment by jacobpoo** [comment]
After a 5 month wait, I have came back. Sadly, the problem persists.
![screenshot from 2018-04-15 17-31-52](https://user-images.githubusercontent.com/24438557/38783680-8799f22a-40d3-11e8-9e7e-e3c1aa1495b0.png)

**Comment by Elbullazul** [comment]
for now I'm busy fixing GTK bugs, but I'm at the end of the TODO list. Once thos bugs are squashed, I'll attack Cinnamon issues.

**Comment by jacobpoo** [comment]
@everyone Are any specific font packages I need in Fedora?

**Comment by Elbullazul** [comment]
no

**Comment by jacobpoo** [comment]
How did the YouTube user English Bob use the theme perfectly on Linux Mint 18.3 when I had it happen since Linux Mint 18.0?

**Comment by jacobpoo** [comment]
example footage: https://youtu.be/TZ_GNdImIFE

**Comment by feren** [comment]
@daemonspudguy He used a different theme.
