### ISSUE TITLE
Unneeded margin in cinnamon window list items

### ISSUE THREAD

**Issue by AndreiMiculita** [B00merang-Project/Windows-XP#30]
Here is what it looks like:
![image](https://user-images.githubusercontent.com/6352172/97222342-8828a900-17ce-11eb-9bec-c315cb250323.png)

Here is the line where it is defined:
https://github.com/B00merang-Project/Windows-XP/blob/2c396d29faaa0687c8fb1cb84541a9e1de675f53/Windows%20XP%20Luna/cinnamon/cinnamon.css#L1729

After removing it:
![image](https://user-images.githubusercontent.com/6352172/97222450-b908de00-17ce-11eb-9219-0aa46a313b6c.png)

**Comment by Elbullazul** [comment]
will look into this

**Comment by Elbullazul** [comment]
414b6d4 fixes this
