### ISSUE TITLE
Pointy white corners

### ISSUE THREAD

**Issue by PlankManOriginal** [B00merang-Project/Windows-XP#31]
Thanks for the theme, just one tiny issue.
On ubuntu mate 20.04 I am seeing white pointy corners, No idea what is causing it and how to fix it.
Thank you, here is a screenshot:
![image](https://user-images.githubusercontent.com/47990368/103180291-256e8f00-489d-11eb-92b7-8a3fb97abaca.png)

**Comment by Elbullazul** [comment]
does it happen with other XP themes as well?

**Comment by Elbullazul** [comment]
confirmed happening with other themes:
![image](https://user-images.githubusercontent.com/15310985/106390880-8ca9c280-63b8-11eb-8d1c-eb85b4f20c03.png)

working on solution

**Comment by MARKMENTAL** [comment]
![image](https://user-images.githubusercontent.com/17995774/106401406-e8dd0880-63f1-11eb-90cf-ddb96de3fa5b.png)
I think i might be able to help with a solution, i got rid of the white corners  by reusing the older xml code from the whistler  metacity theme, editing it to have appropriate dimensions for an XP style theme and renaming the royale dark assets to be compatible with the whistler xml file's definitions.
[metacity-1fix.zip](https://github.com/B00merang-Project/Windows-XP/files/5901085/metacity-1fix.zip)

**Comment by Elbullazul** [comment]
I reinstated the `metacity-1.xml` files with 8f0ca09dfbacf86edc7c974eee12568ffcdf4bc4, but MATE uses `metacity-2.xml` because of the higher version number. If you remove/rename it, it should fall back to `metacity-1.xml`.

Thanks for pointing (no pun intended) out
