### ISSUE TITLE
Top border in borderless mode

### ISSUE THREAD

**Issue by AndreiMiculita** [B00merang-Project/Windows-XP#32]
https://github.com/B00merang-Project/Windows-XP/blob/2c396d29faaa0687c8fb1cb84541a9e1de675f53/Windows%20XP%20Luna/metacity-1/metacity-theme-3.xml#L98-L105

When in borderless mode (e.g. Firefox uses this, to show the tabs at the very top edge of the screen) there is a 6px top border. I assume it's because of the top and bottom button borders defined in `normal` mode, which `borderless` inherits from:

https://github.com/B00merang-Project/Windows-XP/blob/2c396d29faaa0687c8fb1cb84541a9e1de675f53/Windows%20XP%20Luna/metacity-1/metacity-theme-3.xml#L47

Overriding the border by adding: 

```xml
	<border name="button_border" top="0" bottom="0"/>
```
After line 104 seems to fix this. But my DE's weird caching interfered with testing this so I'm not sure if it introduces more issues.

It's an issue because it makes it more difficult to switch tabs, as they are not at the edge of the screen.

**Comment by Elbullazul** [comment]
Can you upload a screenshot of the issue?

**Comment by AndreiMiculita** [comment]
Top border with XP Metallic (happens with all variations):
![](https://imgur.com/nfSwY5K.png)

Note the black bar at the top, I've measured it and it's 6px.

No top border with Linux Mint-Y-Dark (the default theme in Mint):
![](https://imgur.com/9xKHbHI.png)

**Comment by Elbullazul** [comment]
will try the fix later today

**Comment by Elbullazul** [comment]
@AndreiMiculita you were very close. Metacity won't parse the border override without left and right attributes. Including

```xml
<border name="button_border" left="0" right="0" top="1" bottom="0"/>
```

solves this. I'm pushing the fix in a little bit, thanks for pointing out the solution

**Comment by Elbullazul** [comment]
1216024 fixes this
