### ISSUE TITLE
Compatibility with CinnVIIStarkMenu Cinnamon applet

### ISSUE THREAD

**Issue by AndreiMiculita** [B00merang-Project/Windows-XP#33]
Hello,

I saw the issue focusing on the XFCE Whisker menu and thought I'd open a similar issue about Cinnamon.

Not sure how much you've focused on CinnVIIStarkMenu, but to me, it seems like the closest thing to the original Windows XP start menu. Unfortunately, it's not trying to imitate XP, it's trying to imitate Vista/7, so there are some differences.

![stark-xp-menu](https://i.imgur.com/Tu31kkT.png)

The issues I notice are (in order of difficulty as I see it):
* too much padding, especially in the left half
* border between white area & light blue area (sidebar) is missing
* no horizontal yellow line under the top blue rectangle
* separator between favorites and "All Programs" is too thin
* separator between "Downloads" and "Computer" is too thin
* "All Programs" arrow on the left side, should be on the right
* session buttons not in the bottom blue rectangle
* user icon (here showing the "Documents" icon as it's imitating Vista) should be in top blue rectangle.
* session buttons can either be horizontal with no text, or vertical with text; no option to have them horizontal with text, as XP does

**Comment by Elbullazul** [comment]
hello, and thanks for your feedback. A few notes:
- the theme can't override an item's positioning (User picture and "All programs" arrow)
- button text is an option the developer of the extension needs to add. You can open an issue [here](https://github.com/NikoKrause/CinnVIIStarkMenu/issues)

I can address the other issues, as they can be fixed
- [ ] reduce padding on app list
- [ ] border image between columns and yellow highlight on top
- [ ] separator opacity (and possibly thickness)
- [ ] try to move down the session buttons (app list margin bottom & no bottom border?)

**Comment by Elbullazul** [comment]
could not manage to push the buttons into the rectangle, sorry.

Any other suggestions?

**Comment by AndreiMiculita** [comment]
Thanks for the help! I've tried to change some things myself, but I think this is the furthest the theme can go. Other changes will probably have to be made in the applet itself.
