### ISSUE TITLE
Problems with Manjaro

### ISSUE THREAD

**Issue by loloreel** [B00merang-Project/Windows-XP#34]
Hi,
I'm using Manjaro (with XFCE) and there's some problems with the menu bars and with some elements (the buttons and the text boxes are invisible). And also, the theme doesn't work (at all?) on the taskbar and the whisker menu.
![xp1](https://user-images.githubusercontent.com/69239336/107858082-898be900-6e32-11eb-870f-e15d54218009.png)

**Comment by Elbullazul** [comment]
what Xfce version are you on? I think it might include GTK4, which isn't supported yet

**Comment by loloreel** [comment]
I'm using Xfce 4.16

**Comment by Elbullazul** [comment]
officially, it comes with GTK 3.22, but this really smells like GTK 4 to me. Can you check what GTK version you have installed?

**Comment by loloreel** [comment]
I have GTK 3.24

**Comment by Elbullazul** [comment]
where have you installed the theme?

I'd try to remove the `gtk-3.0` folder and rename the `3.20` directory to `3.0`

**Comment by loloreel** [comment]
Ok I'm such an idiot, I was looking into the folder and I realized that there was only like three folders and that the gtk-3.20 one was missing. I didn't copy the theme into my themes folder, instead I used the "Add" option in the settings (which apparently doesn't work well)

**Comment by Elbullazul** [comment]
we all make mistakes from time to time, glad your issue was solved
