### ISSUE TITLE
[BUG] Grouped-windows mouse hover doesn't have background

### ISSUE THREAD

**Issue by Rendellan** [B00merang-Project/Windows-XP#44]
When you hover the pointer on top of a grouped window, it won't have a background which can make selecting a window harder.

Proposed solution:
I tried with Windows XP Luna theme, but if the menu-bottom.png exists, it should work.
Modify cinnamon.css with the following: 

`.grouped-window-list-thumbnail-menu {
	spacing: 6px;
  	padding: 6px 12px 12px 12px;
  	border-image: url("menu-bottom.png") 6;
  	color: #ffffff;
}`

Evidence:
Before hotfix:
![image](https://user-images.githubusercontent.com/14396663/234160564-071f7353-c645-4f0d-99c7-45edfdc7a7fb.png)

After hotfix:
![image](https://user-images.githubusercontent.com/14396663/234160866-e446c8b5-5fd3-409a-8952-0f6a16b96b3e.png)

**Comment by Elbullazul** [comment]
[1c876f9](https://github.com/B00merang-Project/Windows-XP/commit/1c876f9d1a270a7e131f7f628af15b6d6d3c8ce7) addresses this, thanks for your contribution
