### ISSUE TITLE
Is license for images too.

### ISSUE THREAD

**Issue by sagudev** [B00merang-Project/Windows-XP#6]
Is gpl license applicable on all images or are images original from Microsoft.

**Comment by sagudev** [comment]
I will wait for @Elbullazul answer.

**Comment by Elbullazul** [comment]
hello,

we have not intentionally included copyrighted images in here.

the embedded and zune themes use reproductions of the original material.
for the homestead/metallic/luna, I included some from [MintXP](https://www.gnome-look.org/content/show.php/Mint-XP+(GTK3,+GTK2+&+metacity+pack)?content=162905) but can't remember if he ever included a license (gnome-look had an important overhaul and info was lost). If licenses conflict I can eventually migrate to CinnXP assets

royale and royale dark assets are from [CinnXP](https://github.com/ndwarshuis/CinnXP) which are under GPLv3, except royale dark which I replicated myself before CinnXP released their version
