### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by mknepper** [B00merang-Project/Windows-XP#7]
I notice this and the 9x/Redmond themes get very little attention.

**Comment by Elbullazul** [comment]
short answer, no

long answer, needs fixing because current code is very old and dates back to Ubuntu 14.04, so I need to rewrite it in a new codebase built for GTk 3.20 and over

**Comment by Elbullazul** [comment]
https://github.com/B00merang-Project/Windows-XP/releases/tag/1.0
