### ISSUE TITLE
XP Luna GTK2/3

### ISSUE THREAD

**Issue by luigifab38** [B00merang-Project/Windows-XP#8]
Hello

I'm getting some issues with the **XP Luna** theme with GTK 2.24.32 on Debian Testing with Mate 1.12 (I need to update, but I can not find any GTK 3.24 theme that works and I like).

First, the text in window title bar is not centered:
![title](https://user-images.githubusercontent.com/31816829/53562621-207e0e80-3b52-11e9-994c-2413645ae78a.png)

Secondly, I don't know why, but the window button are horrible:
![buttons](https://user-images.githubusercontent.com/31816829/53562953-0133b100-3b53-11e9-8acc-2041282ed425.png)

The widget factory with GTK 2.24.32:
![widgetfactory](https://user-images.githubusercontent.com/31816829/53563011-245e6080-3b53-11e9-8f61-ff6540d47afc.png)

The widget factory with GTK 3.24.5:
![widgetfactory3](https://user-images.githubusercontent.com/31816829/53563080-540d6880-3b53-11e9-9e15-de6075e7f75d.png)

Why the GTK 2 and GTK 3 themes are not the same?

**Comment by Elbullazul** [comment]
fixed a couple of inconsistencies (notebook tabs, buttons). Progressbars are almost impossible to reproduce in GTK2 as they are in GTK 3.

in Windows XP, windows title were aligned to the left: ![winxp](https://cdn1.tekrevue.com/wp-content/uploads/2013/08/20130808_winxp_royaletheme_1.jpg)
