### ISSUE TITLE
Adapt metacity themes for MATE desktop

### ISSUE THREAD

**Issue by danfiscus** [B00merang-Project/Windows-XP#9]
Even after manually fixing or adding all the index.theme files, the window border themes do not work for the Embedded theme, the Royale Dark theme, or the Zune theme. All three are grayed out in the settings menu. I am on Linux Mint 19.1 MATE

**Comment by Elbullazul** [comment]
Metacity-2.xml is not fully functional. I have a rebase planned but I'm super busy this week

**Comment by Elbullazul** [comment]
They should be functional as of now
